<?php

namespace RM\Thorin;

/**
 * Interface for classes that generate and store images in a storage.
 *
 * @author Roman Mátyus
 * @copyright (c) Roman Mátyus 2015
 * @license MIT
 */
interface IGenerator {

	/**
	 * Get usable link for application from Descriptor.
	 * @param  Descriptor $descriptor
	 * @return string
	 */
	function getLink(Descriptor $descriptor);

	/**
	 * Generate Image from link generated by method getLink().
	 * @param  string $link
	 * @return Nette\Utils\Image
	 */
	function getImage($link);
}
